# -*- coding: utf-8 -*-
"""json_Flatten_explode_

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxZFuZObfEJTV6ezGgGAsxJN_RkjEUzy
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import explode,col

spark=SparkSession.builder.appName("json").getOrCreate()

df_json=spark.read.format("json").option("multiline",True).load("/content/json_data.json")

df_json.printSchema()

df_exploded=df_json.select("Course_type","Head_Office_Contact","Institute_Name",explode(col("branches")).alias("branch_data"))
df_exploded.printSchema()
df_exploded.show()

df_exploded_final=df_exploded.select("Course_type","Head_Office_Contact","Institute_Name","branch_data.*")


df_exploded_final.show()

"""Formula : Array ---> Explode , struct ->col.*"""