# -*- coding: utf-8 -*-
"""LiftCapacity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeSYu__zyUtx8gZa6pOGRLnxG-LvbPko
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import collect_list,sum,col,concat_ws
from pyspark.sql.window import Window

spark = SparkSession.builder.appName("Lift").getOrCreate()

lift_data = [
    (1,300),
    (2,350)
]

lift_schema = "id int , capacity_kg int"

lift_df = spark.createDataFrame(data = lift_data , schema = lift_schema)


lift_passengers_data = [
    ('Rahul',85,1),
    ('Adarsh',73,1),
    ('Riti',95,1),
    ('Viraj',80,1),
    ('Vimal',83,2),
    ('Neha',77,2),
    ('Priti',73,2),
    ('Himanshi',85,2)
]

lift_passengers_schema = "passenger_name string , weight_kg int, lift_id int"

lift_passengers_df = spark.createDataFrame(data = lift_passengers_data , schema = lift_passengers_schema)

#lift_df.show()
#lift_passengers_df.show()

lift_passengers=lift_passengers_df.join(lift_df , lift_passengers_df.lift_id == lift_df.id).orderBy(lift_passengers_df.lift_id,lift_passengers_df.weight_kg.asc())
windowspec=Window.partitionBy(lift_passengers_df.lift_id).orderBy(lift_passengers_df.weight_kg.asc())

running_df=lift_passengers.withColumn("running_total",sum(lift_passengers.weight_kg).over(windowspec)).filter(col("running_total")<=col("capacity_kg"))

running_df_final=running_df.groupBy("lift_id").agg(concat_ws(",",collect_list("passenger_name")).alias("passenger_name"))

running_df_final.show(truncate=False)