# -*- coding: utf-8 -*-
"""pageLikes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvH9UjpHx7rvNepzccEGe5EO6hg-rudU
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('practice').getOrCreate()
friends_data = [(1, 2),
(1, 3),
(1, 4),
(2, 1),
(3, 1),
(3, 4),
(4, 1),
(4, 3)]

friend_schema = "user_id int , friend_id int"
friends_df = spark.createDataFrame(data =friends_data , schema = friend_schema )

likes_data = [
(1, 'A'),
(1, 'B'),
(1, 'C'),
(2, 'A'),
(3, 'B'),
(3, 'C'),
(4, 'B')
]


like_schema = "user_id int , page_id string"
likes_df = spark.createDataFrame(data =likes_data , schema = like_schema )
likes_df=likes_df.withColumnRenamed("user_id","userid")
#likes_df.show()
users_df=friends_df.select("user_id").distinct()
pages_df=likes_df.select("page_id").distinct()
total_user_pages=users_df.crossJoin(pages_df)
#total_user_pages.show()

existed_user_pages=likes_df.join(friends_df,likes_df.userid==friends_df.user_id,"outer")
existed_user_pages=existed_user_pages.select("user_id","page_id")
non_existed_user_pages=total_user_pages.subtract(existed_user_pages)
non_existed_user_pages.show()