# -*- coding: utf-8 -*-
"""pivot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13CWV6CaYgpjaZAisq4hdQ8kEwmsfGgq8
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.appName("Match").getOrCreate()

match_data = [
    ("Jadeja", 'Wankhede', 40, 2, 1),
    ("Hardik", 'Eden Gardens', 55, 0, 2),
    ("Jadeja", 'Eden Gardens', 25, 3, 0),
    ("Watson", 'Wankhede', 30, 1, 0),
    ("Hardik", 'Wankhede', 45, 0, 1),
    ("Jadeja", 'Wankhede', 60, 1, 1),
    ("Hardik", 'Eden Gardens', 45, 0, 3),
    ("Hardik", 'Eden Gardens', 30, 4, 0),
    ("Watson", 'Wankhede', 20, 2, 2),
    ("Watson", 'Eden Gardens', 50, 0, 0)
]

match_schema = "Player_Name String , Stadium String , Runs int , Wickets int , Catches int"
match_df = spark.createDataFrame(data = match_data, schema = match_schema)

#match_df.show()

pivoted_df = match_df.groupBy("Player_Name").pivot("Stadium").agg({"Runs": "sum", "Wickets": "sum"})

pivoted_df.show()