# -*- coding: utf-8 -*-
"""studentReportInPyspark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-TUAjqIB5rDXPy-pkfLqDrx1_9fRDCU
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import when,col,round

spark = SparkSession.builder.appName('SparkByExamples.com').getOrCreate()

_student = [(1,'Suresh'),(2,'David'),(3,'Sakib')]
_student_schema = "student_id int , student_name string"

_marks = [(1,'pyspark',90),
          (1,'sql',100),
          (2,'sql',70),
          (2,'pyspark',60),
          (3,'sql',30),
          (3,'pyspark',20)
          ]
_marks_schema = "student_id int , subject_name string , marks int"

#Create Student dataFrame
student_df = spark.createDataFrame(data = _student , schema = _student_schema)
#student_df.show()

#Create Marks DataFrame
marks_df = spark.createDataFrame(data = _marks , schema = _marks_schema)
#marks_df.show()

df_sum_marks=marks_df.groupBy('student_id').sum('marks')
df_sum_marks=df_sum_marks.withColumnRenamed('sum(marks)','total_marks')
#df_sum_marks.show()

df=student_df.join(df_sum_marks,student_df.student_id==df_sum_marks.student_id).select(student_df.student_id,student_df.student_name,df_sum_marks.total_marks)
df=df.withColumn("result",when (col("total_marks")/200>=.7, "Distinction").when(col("total_marks")/200>=.6, "First Class").when(col("total_marks")/200>=.5, "Second Class").when(col("total_marks")/200>=.4, "First Class").otherwise("Fail"))
df=df.withColumn("percentage",((col("total_marks")/200)*100).cast("int")).drop('total_marks').orderBy(col("percentage").desc())
df.show()