# -*- coding: utf-8 -*-
"""tigerAnalytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBt-xUO7drjZ4gz_1h_ADdG0xm5X7lOE
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import first,last,row_number,min,max
from pyspark.sql.window import Window

spark = SparkSession.builder.appName("Flight").getOrCreate()

flights_data = [(1,'Flight1' , 'Delhi' , 'Hyderabad'),
                (1,'Flight2' , 'Hyderabad' , 'Kochi'),
                (1,'Flight3' , 'Kochi' , 'Mangalore'),
                (2,'Flight1' , 'Mumbai' , 'Ayodhya'),
                (2,'Flight2' , 'Ayodhya' , 'Gorakhpur')
                ]

_schema = "cust_id int, flight_id string , origin string , destination string"

df_flight = spark.createDataFrame(data = flights_data , schema= _schema)
df_flight.show()


print("Method *****1*****")
df_flight1=df_flight.groupBy("cust_id").agg(first("origin").alias("origin"),last("destination").alias("destination"))
#df_flight1.show()

print("Method *****2*****")
WindowSpec=Window.partitionBy("cust_id").orderBy("flight_id")
df_flight2=df_flight.withColumn("rownumber",row_number().over(WindowSpec))
df_flight2=df_flight2.groupBy("cust_id").agg(min("rownumber").alias("start"),max("rownumber").alias("end"))
df_flight2.show()

df_f=df_flight2.join(df_flight,on=["cust_id"],how="inner").drop(df_flight.flight_id,df_flight.origin,df_flight.destination)
df_f.show()
df_f.groupBy("cust_id").agg(first("origin").alias("origin"),last("destination").alias("destination")).show()