# -*- coding: utf-8 -*-
"""unpivot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYdMr2jk_1jtRA-1AAxkCGdBDHa0S76b
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, avg, when
spark = SparkSession.builder.appName("CricketData").getOrCreate()

cricket_data = [("Virat Kohli", 85, 100, 75),
        ("Steve Smith", 90, 105, 80),
        ("Kane Williamson", 88, 95, 70)]

df = spark.createDataFrame(cricket_data, ["Player", "Match1", "Match2", "Match3"])

df.show()
columns = ["Match1", "Match2","Match3"]
expr = "stack({}, {})".format(
    len(columns),
    ", ".join(["'{}', {}".format(c, c) for c in columns])
)
df_unpivot=df.selectExpr("Player", f"{expr} as (match, runs)")
df_unpivot.show()